name: Generate project.json

on:
  push:
    branches: [master]

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js (for script)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run generator script
        run: node .github/scripts/generateProjectJson.js

      - name: Push changes
        run: |
          git config user.name "ikshv"
          git config user.email "ikshvartsman@gmail.com"
          git add project.json
          git commit -m "Auto-generate project.json from README"
          git push https://x-access-token:${{ secrets.GH_API_TOKEN }}@github.com/${{ github.repository }} HEAD:main
