name: Update Project Data and Notify Portfolio

on:
  push:
    branches: [master]

jobs:
  update-project-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run generator script
        run: node .github/scripts/generateProjectJson.js

      - name: Commit and push project.json changes
        run: |
          git config user.name "ikshv"
          git config user.email "ikshvartsman@gmail.com"
          git add project.json
          if ! git diff --cached --quiet; then
            git commit -m "Auto-generate project.json from README [skip ci]"
            git push https://x-access-token:${{ secrets.GH_API_TOKEN }}@github.com/${{ github.repository }}.git HEAD:master
          else
            echo "No changes to commit"
          fi

      - name: Trigger Portfolio Update
        run: |
          curl -X POST https://api.github.com/repos/ikshv/ikshv.github.io/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GH_API_TOKEN }}" \
          -d '{"event_type": "project-json-update", "client_payload": {"repo": "${{ github.repository }}"}}'
